### ISSUE TITLE
DNS server that is configured via DHCP, is not shown in redfish command

### ISSUE THREAD

**Issue by prkatti1** [openbmc/phosphor-networkd#29]
DNS server that is configured via DHCP, is not shown in redfish command.
Both nameserver and staticnameserver fields are empty.
This gives the impression that no DNS server is configured on BMC although DNS servers are configured which is visible in /etc/resolv.conf

**Comment by manojkiraneda** [comment]
Resolved by :
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-networkd/+/24224/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24229/

**Comment by ratagupt** [comment]
Me and William had a discussion on the same, needs to change the Ethernet D-bus interface and add the following properties
Currently, there is nameserver property which keeps the static DNS entries
Proposal is to have two properties instead of one. 
1) Nameservers: This will keep the DHCP as well as the Static DNS entries
2) StaticNameservers: This will keep only the Static DNS entries.

This is aligned with Redfish data modeling.

**Comment by manojkiraneda** [comment]
Code is Up for Review :
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/26060/
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-networkd/+/26115/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/25804/

**Comment by manojkiraneda** [comment]
The code is merged in master.

**Comment by manojkiraneda** [comment]
@prkatti1 can we close this issue ? as it is already merged.

**Comment by ratagupt** [comment]
Let's close this one
