### ISSUE TITLE
BMC is not extracting Domain Name & configuring it on BMC

### ISSUE THREAD

**Issue by swe12345** [openbmc/phosphor-networkd#47]
Problem Description
----------
BMC is not extracting Domain Name & configuring it on BMC

Steps:
Enable UseDomainName dhcp property.
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"DHCPv4" : {"UseDomainName":true}}' [https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth1](https://redfish/v1/Managers/bmc/EthernetInterfaces/eth1)

Check whether property is set or no using following command:
curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET  https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

Send DHCP request and see if bmc uses domain name offered by DHCP server:

Expectation:
resolv.conf should get updated with line like below:
search something.com

**Comment by swe12345** [comment]
@sunharis

**Comment by swe12345** [comment]
@ratagupt

**Comment by sunharis** [comment]
@ratagupt @wak-google The issue here is that the /etc/resolv.conf is not getting the `<something.com>` updated as the `search` keyword value even if the DHCP server sends that value with the DHCP lease. So from the BMC, if you ping a hostname, it does not add the `<something.com>` to the hostname 

PS: The DHCP supplied DNS server IP is updated as expected for `nameserver`

**Comment by sunharis** [comment]
System already has the systemd fix https://github.com/systemd/systemd/issues/8174  
Any changes needed on networkd ? @wak-google @ratagupt please suggest
